# Site settings
title: 구주희의 블로그 Juhee Ku's Blog
url: "http://zzsleepzz630.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Seoul
description: >
  description

# Your information
email: zzsleepzz630@naver.com
author: 구주희
# avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
avatar: "//github.com/yunho0130/yunho0130.github.io/blob/master/_jpg/yunhomaeng.png"
profile: <br> 상명대학교 경영학부 201610573 구주희
#twitter_username: twitter_username
github_username:  zzsleepzz630

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: maengdev   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: jekyll-theme-dinky
